name: paldes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_screenutil:
  flutter_cupertino_date_picker:
  numberpicker:
  badges:
  flutter_riverpod:
  hooks_riverpod:
  progress_dialog:
  dio:
  shared_preferences:
  image_picker:
  flutter_styled_toast:
  cloud_firestore:
  firebase_core: 1.2.0
  firebase_auth:
  firebase_messaging:
  firebase_storage:
  google_fonts:
  intl:
  numeric_keyboard:
  flutter_launcher_icons:
#  qr_flutter: ^1.1.1
  barcode_widget:
#  barcode_scanner:
  flutter_barcode_scanner:
  permission_handler:
#  barcode_scan:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/gymui/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Futura Md BT
     fonts:
       - asset: assets/fonts/FutuBd.ttf
       - asset: assets/fonts/FutuBdIt.ttf
       - asset: assets/fonts/FutuMd.ttf
       - asset: assets/fonts/FutuMdIt.ttf
       - asset: assets/fonts/FUTURAB.ttf
       - asset: assets/fonts/FuturaBoldBT.ttf
       - asset: assets/fonts/FuturaBoldItalicBT.ttf
       - asset: assets/fonts/FuturaMediumBT.ttf
       - asset: assets/fonts/FuturaMediumItalicBT.ttf

   - family: Futura Bk BT
     fonts:
       - asset: assets/fonts/FutuBk.ttf
       - asset: assets/fonts/FutuBkIt.ttf
       - asset: assets/fonts/Futura_20Medium_20BT.ttf
       - asset: assets/fonts/FuturaBookBT.ttf
       - asset: assets/fonts/FuturaBookItalicBT.ttf
         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo.png"